### ISSUE TITLE
Do we want to use `transformers`?

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/lerobot#112]
I'd really go against establishing transformers as a dependency of lerobot and importing their whole library just to use the `PretrainedConfig` (or even other components). I think in this case it's very overkill and wouldn't necessarily fit our needs right now. The class is ~1000 lines of code - which we can copy into our lib anyway - and looks way more mature and feature-rich than what — IMO — we need and have with the rest of our code base.

Copying code is even part of [Transformers' philosophy](https://huggingface.co/blog/transformers-design-philosophy) — which we *do* copy.

_Originally posted by @aliberts in https://github.com/huggingface/lerobot/pull/101#discussion_r1581860998_

**Comment by qgallouedec** [comment]
`transformers` comes with a lot of features (utilities for handling the HF Hub, `Trainer`, Auto classes, pipeline for inference, `PreTrained[Model/Config]` etc). On the one hand, it would allow us to benefit from all these nice features and to integrate our work more strongly with the HF ecosystem, but on the other hand, the transformer components are not required for LeRobot to work. And adding a dependency that isn't necessary is generally a bad choice. WDYT @alexander-soare @thomwolf etc.

**Comment by alexander-soare** [comment]
I agree that we shouldn't add the dependency if we only need a couple hundred lines of code of functionality from it. But question, why wouln't be use `PytorchModelHubMixin` from the `huggingface-hub` repo? I'd say basing off a more central dependency like that makes more sense than piggybacking on `transformers`?

**Comment by aliberts** [comment]
> why wouln't be use PytorchModelHubMixin from the huggingface-hub repo?

I like this idea, it looks more like what we actually want, plus it's already a dependency of LeRobot.
