### ISSUE TITLE
Visualization during training

### ISSUE THREAD

**Issue by fabawi** [huggingface/lerobot#141]
Thank you for this great framework. I tried to train a model following the example:

```python lerobot/scripts/train.py     policy=act     env=aloha     env.task=AlohaInsertion-v0     dataset_repo_id=lerobot/aloha_sim_insertion_human```

But it seems the `render_mode` is hardcoded as `rgb_array` in `lerobot/common/envs/factory.py` and the environment does not support `human` rendering.  It would be very useful for debugging the models, more so if it could somehow be linked to the rerun GUI. 

I was wondering if there are plans to support non-headless training. If not, do you have any tips or recommendations for visualization during training/evaluation using any of  the following approaches: 
1. rerun dataset visualizer
2. [dm_control viewer](https://github.com/google-deepmind/dm_control/blob/main/dm_control/viewer/README.md)
3. Wrapping the make env with `gymnasium.experimental.wrappers.HumanRenderingV0`

**NOTE**: I naively tried wrapping the make in `lerobot/common/envs/factory.py` with `HumanRenderingV0`. That visualizes the environment for a few iterations and quickly spawns a new window for every episode. I'm not sure this is how it should be done but this is certainly not the best approach:

```
env = env_cls(
        [
            lambda: HumanRenderingV0(gym.make(gym_handle, disable_env_checker=True, **kwargs)).reset()
            for _ in range(n_envs if n_envs is not None else cfg.eval.batch_size)
        ]
    )
 ```

**Comment by Cadene** [comment]
I would recommend using wandb (which is set by default if you do `wandb login`). As you can see on the top left, we upload videos of the evaluation during training:
<img width="1179" alt="wandb" src="https://github.com/huggingface/lerobot/assets/4681518/33e3f890-1f45-4b31-9e7a-f2c7b3b73385">

See the training section of the README for more info: https://github.com/huggingface/lerobot?tab=readme-ov-file#train-your-own-policy

We actually run evaluation on multiple parallel environments and only send the rendering of the first one to wandb:
https://github.com/huggingface/lerobot/blob/main/lerobot/scripts/train.py#L353

Note that we render 4 episodes (see: https://github.com/huggingface/lerobot/blob/main/lerobot/scripts/train.py#L348) that you can visualize as mp4 in your experiment directory.

"I was wondering if there are plans to support non-headless training."
-> We don't plan to do so. We tend to prefer headless training as a lot of people directly work on their GPU machine through ssh.
If you have a specific use case in mind that requires non-headless, let us know.

**Comment by Cadene** [comment]
Also take a look at this example where it would be easier to add non-headless visualization by setting `render_mode="human"`:
https://github.com/huggingface/lerobot/blob/main/examples/2_evaluate_pretrained_policy.py#L35-L39

**Comment by fabawi** [comment]
Thank you, I didn't realize that the videos were uploaded to wandb (it didn't upload any videos in my case, but probably something wrong with my setup). I can't think of a pressing reason for non-headless training.  But down the line, an online training paradigm with human feedback might require such a mechanism. The wandb video upload should be sufficient for now

**Comment by alexander-soare** [comment]
@fabawi also, the training outputs folder should contain videos 
![image](https://github.com/huggingface/lerobot/assets/16543381/0f1f4776-7dd9-4edc-9fea-616fbfa9caf6)

**Comment by alexander-soare** [comment]
Closed, as it looks like you're satisfied with the outcome for now :)
