### ISSUE TITLE
The LeRobot TODO hyperlink in CONTRIBUTING.md is not working

### ISSUE THREAD

**Issue by vinayakkgarg** [huggingface/lerobot#142]
### System Info

```Shell
The "LeRobot TODO" hyperlink in the contribution guide (lerobot/CONTRIBUTING.md) redirects to a 404 page.
The hyperlink currently redirects to: https://github.com/orgs/huggingface/projects/46
```

### Reproduction

1. Click the "LeRobot TODO" hyperlink in the contribution guide (lerobot/CONTRIBUTING.md)

### Expected behavior

The hyperlink should ideally redirect to a page with a list of to-do tasks.

**Comment by alexander-soare** [comment]
Thanks @vinayakkgarg for reporting this. We forgot to make the board public. We'll get it organized and update the link shortly. cc @Cadene @aliberts

**Comment by Cadene** [comment]
Fixed ;) https://github.com/orgs/huggingface/projects/46
