### ISSUE TITLE
Tests do not pass when just poetry text extras installed

### ISSUE THREAD

**Issue by AshisGhosh** [huggingface/lerobot#173]
### System Info

```Shell
Tested on `main`, commit: 1249aee
```

### Information

- [X] One of the scripts in the examples/ folder of LeRobot
- [ ] My own task or dataset (give details below)

### Reproduction

`gym_pusht` is a missing requirement.

1. Follow https://github.com/huggingface/lerobot/blob/main/CONTRIBUTING.md
2. Create a new conda env 
```
conda create -y -n lerobot-dev python=3.10 && conda activate lerobot-dev
```
3. Install limited extras including test
```
poetry install --sync --extras "dev test"
```
4. Run all tests 
```
DATA_DIR="tests/data" python -m pytest -sv ./tests
```

Received the following error:

```
>   ???
E   ModuleNotFoundError: No module named 'gym_pusht'

<string>:8: ModuleNotFoundError
========================================================= short test summary info ==========================================================
FAILED tests/test_examples.py::test_examples_3_and_2 - ModuleNotFoundError: No module named 'gym_pusht'
================================================ 1 failed, 39 passed, 25 skipped in 20.48s =================================================
```

### Expected behavior

All tests to pass.

**Comment by aliberts** [comment]
Hi, thank you for reporting this!
I guess we haven't tested this since #81, I will update the tests appropriately.
