### ISSUE TITLE
Enable visualisation of local datasets by adding `root` arg

### ISSUE THREAD

**Issue by tlpss** [huggingface/lerobot#248]
I am trying to convert my dataset to a `LeRobotDataset` and have implemented a conversion script. 

I wanted to visualize the dataset locally before uploading or continuing, but the visualization script lacks a `root` arg to enable loading from a local dataset (used in the `LeRobotDataset` init to distinguish between local or remote)

I added this locally and then I was able to visualize the dataset in rerun

![image](https://github.com/huggingface/lerobot/assets/37955681/03d42d5b-5d02-4281-9120-d283467f19d2)

It would be convenient if this would be added to the main branch! 
It is a very small change and I would be willing to make a PR for this.

**Comment by Cadene** [comment]
@tlpss Sorry for the lack of documentation. You can already load a LeRobotDataset stored locally with:
```
export DATA_DIR="data"
```
See: https://github.com/huggingface/lerobot/blob/main/lerobot/common/datasets/lerobot_dataset.py#L38-L47

Happy to add `root` arg in visualize_dataset.py. By any chance, would you have time to put up a PR? Thanks!

**Comment by tlpss** [comment]
> You can already load a LeRobotDataset stored locally with:

Thanks for pointing out, I hadn't seen that


> By any chance, would you have time to put up a PR? Thanks!

 sure, I'll make a PR for this!
