### ISSUE TITLE
Make naming scheme for local data folders less strict

### ISSUE THREAD

**Issue by tlpss** [huggingface/lerobot#251]
Atm, the push_to_hub script requires the local data folder to be named `<data-dir>/<repo-id>_raw`.  Imo this creates unnecessary friction for the user. I had to create some symlinks before I could create and upload my dataset.

I would suggest to simply use `data-dir` for the parent directory of the local data folder, and to provide a seperate output dir parameter for local storage.

**Comment by aliberts** [comment]
Hi, yes we are working on it this week (#231) ;)
