### ISSUE TITLE
Is there any chance to use this repository under python3.8?

### ISSUE THREAD

**Issue by calcualatexzy** [huggingface/lerobot#256]
Thanks for the excellent work!

Since my custom environment is under isaac-gym, which is deprecated and only allowed on python3.6-3.8, could you help me easily use lerobot under python3.8?

**Comment by aliberts** [comment]
Hi there, thank you!

Unfortunately, some of our dependencies require `python>3.9`.
Additionally, Python 3.8 will reach end of life by [2024-10](https://devguide.python.org/versions/)

If you really need 3.8 you can try and downgrade those dependencies until you get it to work but we can't guarantee it. If you manage to get it to work, don't hesitate to paste your `.lock` file here ;)
