### ISSUE TITLE
how to eval the policy trained by lerobot in real env?

### ISSUE THREAD

**Issue by cong1024** [huggingface/lerobot#305]
### System Info

```Shell
how to eval the policy trained by lerobot in real env?
```

### Information

- [ ] One of the scripts in the examples/ folder of LeRobot
- [ ] My own task or dataset (give details below)

### Reproduction

in the code, i have not found any solution to transfer policy rollout to real env, please help me figure it out

### Expected behavior

how to infer the policy trained by lerobot in real env?

**Comment by Cadene** [comment]
@cong1024 We are working on a PR + tutorials: https://github.com/huggingface/lerobot/pull/288

**Comment by cong1024** [comment]
thanks a lot!

**Comment by ysyyork** [comment]
@Cadene this is awesome! cant wait to see the work merged

**Comment by cong1024** [comment]
@Cadene Nice, I see the pr has been merged,  by now only support the robot koch, will there be more support for other type of robot for example aloha or unitree or  so-100 robot in future?  thx

**Comment by aliberts** [comment]
> @Cadene Nice, I see the pr has been merged, by now only support the robot koch, will there be more support for other type of robot for example aloha or unitree or so-100 robot in future? thx

Hi there, yes we are working on adding support for more robots in the near future, including SO-100 and Aloha ;)

I'm closing this in the meantime, feel free to reopen if needed.
