### ISSUE TITLE
UnboundLocalError: local variable 'safe_action' referenced before assignment

### ISSUE THREAD

**Issue by littlecay** [huggingface/lerobot#449]
>>> robot.connect()
Connecting main follower arm.
Connecting main leader arm.
Activating torque on main follower arm.
>>> import tqdm
>>> seconds = 30
>>> frequency = 200
>>> for _ in tqdm.tqdm(range(seconds*frequency)):
...     leader_pos = robot.leader_arms["main"].read("Present_Position")
...     robot.follower_arms["main"].write("Goal_Position", leader_pos)
...
100%|█████████████████████████████████████████████████████████████████████████████| 6000/6000 [00:30<00:00, 199.57it/s]
>>> for _ in tqdm.tqdm(range(seconds*frequency)):
...     robot.teleop_step()
...
  0%|                                                                                         | 0/6000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\deeplearning\robotic\lerobot-main\lerobot\common\robot_devices\robots\koch.py", line 434, in teleop_step
    self.send_action(torch.tensor(follower_goal_pos[name]), [name])
  File "D:\deeplearning\robotic\lerobot-main\lerobot\common\robot_devices\robots\koch.py", line 563, in send_action
    follower_goal_pos[name] = safe_action.numpy()
UnboundLocalError: local variable 'safe_action' referenced before assignment

I met this when I follows the 7.get_start_with_real_robot.md, and I found:

            if self.config.max_relative_target is not None:
                if not isinstance(self.config.max_relative_target, list):
                    max_relative_target = [self.config.max_relative_target for _ in range(from_idx, to_idx)]
                max_relative_target = torch.tensor(self.config.max_relative_target)
                # Cap relative action target magnitude for safety.
                current_pos = torch.tensor(self.follower_arms[name].read("Present_Position"))
                diff = this_action - current_pos
                safe_diff = torch.minimum(diff, max_relative_target)
                safe_diff = torch.maximum(safe_diff, -max_relative_target)
                safe_action = current_pos + safe_diff
                if not torch.allclose(safe_action, action):
                    logging.warning(
                        "Relative action magnitude had to be clamped to be safe.\n"
                        f"  requested relative action target: {diff}\n"
                        f"    clamped relative action target: {safe_diff}"
                    )

            follower_goal_pos[name] = safe_action.numpy()
            from_idx = to_idx
in koch.py 542~564. If self.config.max_relative_target is None, then safe_action is no where to define. Is this a bug, or some mis operation by myself?

**Comment by Cadene** [comment]
Are you on main? This issue has been fixed a few days ago.

```bash
git fetch origin main
git checkout origin/main
```
