### ISSUE TITLE
Data version conversion

### ISSUE THREAD

**Issue by Henry-Ellis** [huggingface/lerobot#501]
I see the data set on the huggingface version changes from v1.6 to v2, I see https://github.com/huggingface/lerobot/pull/461, But there is no this file lerobot/common/datasets/v2 / convert_dataset_v1_to_v2 py, please give clear detailed tutorial or example shows that this process?

**Comment by aliberts** [comment]
Hi, we're still working on that PR. Until it gets merged, you should keep using v1.6 if you're on the main branch. The conversion script is on the branch of that PR but they're not fully ready yet.
