### ISSUE TITLE
Replay buffer needs to handle observation steps, prediction horizon, and rollout horizon

### ISSUE THREAD

**Issue by alexander-soare** [huggingface/lerobot#51]
Consider a policy that:

- Takes as input a total of $N_o$ environment observations, $1$ from now and $N_o - 1$ from the past.
- Internally generates a horizon of $N_h$ actions to execute in the environment, starting from the first (maybe past) observation.
- Only ends up executing $N_r <= N_h - (N_o - 1)$ of those actions on the environment.

Let's take an example: $N_o = 2$, $N_h = 8$, $N_r = 4$.

![image](https://github.com/huggingface/lerobot/assets/16543381/d0bc71ac-70b1-4abb-8e8e-1a88d87c7a01)

To be clear, the whole purpose of having a longer prediction horizon than actually needed for rollout is to train a policy with longer horizon modelling capabilities than it will actually be used for (in hopes that this improves the performance in rollouts).

For training such a policy it's important every bit of the replay buffer ends up in the window of "r"s I drew above at some point in the training process. To illustrate what I mean: suppose the sampler is only aware of $N_h$ but is not aware of $N_o$ and $N_r$. Then given an episode with 16 time steps, the sampler has 8 possible sequences it can sample:

![bad](https://github.com/huggingface/lerobot/assets/16543381/97dac702-f9e4-4525-a1b5-5f93829ce300)

But this means the policy is never trained to generate an action trajectory that can complete the task in $N_r$ steps! During rollout, the policy might get close to completing a task, but would struggle to finish it (and this is exactly what happened: see https://github.com/huggingface/lerobot/pull/41#issue-2199930267).

The sampler must be able to do this:

![good](https://github.com/huggingface/lerobot/assets/16543381/290d3a1f-7fd3-4fd7-8a24-11ef45a9be8f)

Of course, that means we'd need to fill in the blanks. For example, at this position, the red letters aren't in the actual replay buffer so we need to somehow fill them in:

![image](https://github.com/huggingface/lerobot/assets/16543381/d6d69110-0b88-403d-8cbf-f3d90d941493)

or another example:

![image](https://github.com/huggingface/lerobot/assets/16543381/af96cdbf-9fab-4702-be11-2a4cc392e9b9)

One strategy could be padding with copies.

---

Currently, the TorchRL sample does the first variant of sample (without appropriate padding). We need to come up with a solution for padding correctly.

**Comment by Cadene** [comment]
Addressed by https://github.com/huggingface/lerobot/pull/64
