### ISSUE TITLE
Keep the last frame when preparing datasets

### ISSUE THREAD

**Issue by alexander-soare** [huggingface/lerobot#52]
Currently, in `_download_and_preproc_obsolete` for PushT and Aloha, we are dropping the last frame meaning that we potentially don't keep the action that leads to the success condition. Also, we prepared the initial buffer as all copies of the first frame `td_data = ep_td[0].expand(total_frames).memmap_like(self.root / f"{self.dataset_id}")`, then populated the buffer with the frames: `td_data[idxtd : idxtd + len(ep_td)] = ep_td`, meaning that the end of the buffer would have a bunch of nonsensical copies of the first frame.

See this PR https://github.com/huggingface/lerobot/pull/50

**Comment by alexander-soare** [comment]
@Cadene this is yours now as you're doing the removal of torchrl. I assume it's no longer an issue but will leave you to close it.

**Comment by Cadene** [comment]
Addressed by https://github.com/huggingface/lerobot/pull/64
