### ISSUE TITLE
Waveshare ST3215 servo support

### ISSUE THREAD

**Issue by rabhishek100** [huggingface/lerobot#532]
I am from India and I am able to only find the Waveshare ST3215 servo and Waveshare serial bus servo driver board locally here. Will the software work with that motor or do we need need to write a separate motor class for that to work?

**Comment by rabhishek100** [comment]
The same code works!

**Comment by Jeevesh2009** [comment]
Hey @rabhishek100 did you get any error like this while calibrating. I can run scan_motors.py and can read position values for all 6 motors for 2 arms.

![Image](https://github.com/user-attachments/assets/3eab9cd8-c014-41a7-9ef3-7e0ada2aed8a)

Even with the arduino I am able to write pos for multiple motors but i am not able to read synchrounosly Its not even there in their SCServo Library(SMS_STS)

**Comment by Jeevesh2009** [comment]
Hi @rabhishek100 , I ended up realizing that the frequency of reading the values from the motors is very low , try teleoperating fewer motors you wont get the error, I am able to teleoperate all 6 motors if i am adding some wait_length in the code. But since the freq is low and again i am inducing some delay , the motion is very shaky. Can anyone help? @kashif @danieldk @co42 I am using waveshare st3215 HS servos.

**Comment by theharshithh-work** [comment]
hey @rabhishek100 did the calibration script work for you?

**Comment by ananth-pal** [comment]
hey @rabhishek100 I've run into the same issue. Did the waveshare motors work?

**Comment by rabhishek100** [comment]
> hey [@rabhishek100](https://github.com/rabhishek100) I've run into the same issue. Did the waveshare motors work?

Yes

**Comment by ananth-pal** [comment]
Got a runtime error as follows after using Waveshare replacement for ID 3:

RuntimeError: Some Motors use different firmware versions:
{1: '3.10', 2: '3.10', 3: '3.9', 4: '3.10', 5: '3.10', 6: '3.10'}
Update their firmware first using Feetech's software. Visit https://www.feetechrc.com/software.

Did you solve this? @rabhishek100 @Jeevesh2009 @theharshithh-work
