### ISSUE TITLE
Reproducing aloha/act results

### ISSUE THREAD

**Issue by Cadene** [huggingface/lerobot#62]
Even when evaluating a model trained on original aloha act codebase, the policy is shaky. We need to investigate.

https://github.com/huggingface/lerobot/assets/4681518/31a9c8ad-a27f-484c-8290-2469922a6a7b

**Comment by alexander-soare** [comment]
Is this true when evaluating on the aloha act codebase as well?

**Comment by alexander-soare** [comment]
This is no longer the case after some fixes to the dataset.
